### ISSUE TITLE
orthofinder "freezes" within the first minute of run, when using many species

### ISSUE THREAD

**Issue by assafwww** [davidemms/OrthoFinder#145]
Dear Orthofinder developers,

I'm encountering a problem when running Orthofinder with more than few fasta files.
Basically, within the first minute of run, orthofinder creates in workingDirectory:
* blast databases (BlastDBSpecies*.* files)
* SpeciesIDs.txt , SequenceIDs.txt
* species*.fa fasta files
But then it does not proceed to the next step (running blast, and producing Blast*_*.txt files).
In my case the problem happens with 14 species, but the program seems to complete fine with 4 species (giving all expected files and dirs, and completing apparently without any errors).

I'm using a slurm cloud, and call the program as so:
```

sbatch -N1 -n56 --ntasks-per-node=56 --mem=760000 -p q \
	-o $dirIn/out.out -e $dirIn/err.err \
	--wrap "python $orthofinder -f \"$dirIn" -t 56"
```

thanks in advance,
Assaf

**Comment by assafwww** [comment]
Hi David,
thanks :)
The slurm setting (as above) means that all threads must run on a single node. From the graphs of the Slurm node processor/memory state there is no activity after <1min. I'm testing Orthofinder now with the exact same setting, but on a subset of 8 species (instead of 14) and it seems to work fine. I'll try to further check with the system administrator.

thanks again,
Assaf

**Comment by davidemms** [comment]
Hi Assaf

Have you got any further information on this? It would be helpful to see the OrthoFinder output printed to screen for this (I think slurm puts this in a file). Did the system administrator have any extra information? Would you be able to find out if any processes are running after it appears to halt? 

Also, could you try it with the latest version of OrthoFinder. OrthoFinder creates some worker processes at the beginning (it reduces the memory usage caused by process forking which is important for large analyses). These processes need to be terminated correctly at the end of a run. It could be that the run failed but that these processes weren't terminated causing it to hanf=g. This should be resolved in the latest version.

Thanks
David

**Comment by assafwww** [comment]
Hi David,

I am testing it again with the latest version, but it still fails. I'll ask the administrator about these issues.
Yet, there's possibly certain hint - in Orthofinder working directory, the blast databases should look like so,
BlastDBSpecies*.psq
BlastDBSpecies*.pin
BlastDBSpecies*.phr

where * should be a number 0...n (n=13 in my case)

yet, it seems to stop at n=8, with the following output:

BlastDBSpecies8.00.psq
BlastDBSpecies8.00.pin
BlastDBSpecies8.00.phr
These ".00" are unexpected i would guess ...

many thanks !
Assaf

**Comment by davidemms** [comment]
Hi Assaf

Yes that's intriguing, although probably not enough info yet to work out what's going on.

Would you be able to try running commands to produce the Blast databases and do a search yourself and see what happens? In the working directory (or specifying the full paths to the files), run:

```
makeblastdb -dbtype prot -in Species1.fa -out BlastDBSpecies1
blastp -outfmt 6 -evalue 0.001 -query Species0.fa -db BlastDBSpecies1 -out Blast0_1.txt
```

Many thanks
David

**Comment by MarkChristianHarrison** [comment]
Hi,
I'm experiencing  a similar error without any kind of queuing system. For me it stops working on the 5th database out of 7. Although it doesn't crash, it just freezes after the first minute. Here's the stdout:

#####
OrthoFinder version 2.2.7 Copyright (C) 2014 David Emms

2018-09-25 17:17:57 : Starting OrthoFinder
10 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "makeblastdb -help" - ok
Test can run "blastp -help" - ok
Test can run "mcl -h" - ok
Test can run "fastme -i /global/group/home/harrisom/Mnat_Soldiers/Orthology/SimpleTest.phy -o /global/group/home/harrisom/Mnat_Soldiers/Orthology/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2018-09-25 17:18:00 : Creating Blast database 1 of 7
2018-09-25 17:18:01 : Creating Blast database 2 of 7
2018-09-25 17:18:02 : Creating Blast database 3 of 7
2018-09-25 17:18:04 : Creating Blast database 4 of 7
2018-09-25 17:18:05 : Creating Blast database 5 of 7

#####

For the 5th database the following files are produced:
BlastDBSpecies4.00.pin
BlastDBSpecies4.00.psq
BlastDBSpecies4.00.phr


Any ideas?
Thanks,
Mark

**Comment by MarkChristianHarrison** [comment]
Sorry, I posted too soon. The problematic fasta file was the only one containing "." as terminal stop codons. After removing these the problem was resolved. This is quite interesting since this doesn't normally cause problems for makeblastdb, it just creates warnings that these invalid residues are ignored.
Best,
Mark

**Comment by davidemms** [comment]
Hi Mark

Do you know what version of makeblastdb you were using? I've tried with version 2.2.28 and I don't see this behaviour, I'm wondering if I'm not taking the right steps to reproduce it.

Thanks
David

**Comment by MarkChristianHarrison** [comment]
Hi David,
I'm using version 2.7.1+
But after removing the stop codons it worked fine.
Thanks,
Mark

**Comment by davidemms** [comment]
Thanks, I've managed to reproduce the error now. 

I'm thinking not all users will be as smart and so might not be able to figure out the solution so I'm seeing what OrthoFinder can do to make clear the error. The hang occurred because of loads of stderr messages from makeblastdb. OrthoFinder should avoid this causing a hang and should alert the user to the problem if possible, but its a bit tricky....

**Comment by davidemms** [comment]
Hi

This issue should now be resolved. The hang was occurring when an external program like BLAST was producing too much output to stderr and was causing a hang. It's a known occurrence in python and I've now re-coded OrthoFinder using a different approach that doesn't suffer from this problem.

I've updated a little the behaviour the user observes. In general, to keep the output tidy OrthoFinder doesn't print out the output from other programs it calls as it's not that informative and there's often a lot of it--or vast quantities in some cases! However, now OrthoFinder monitors this output a bit more and in cases where it looks like there's a problem it prints out the stderr and stdout. This should help users identify problems with input files etc. if things go wrong. I _think_ this is a good solution, but it might need further improvement to get to a solution that works effectively for users.

David
