### ISSUE TITLE
-S diamond only working in orthofinder install dir

### ISSUE THREAD

**Issue by thackl** [davidemms/OrthoFinder#87]
Hi David,

When running `cd /path/to/OrthoFinder-1.1.8; /path/to/orthofinder -S diamond ...` in its install dir, diamond works (and is also shown as a valid choice in the usage). When running `cd somewhere/; path/to/orthofinder -S diamond ...`, I get the error 
```
Invalid argument for option -S: diamond
Valid options are: {blast}
```
Also `-h` no longer lists diamond as a valid option. The same seems to be the case for muscle. Copying the config.json into the directory I'm running orthofinder from fixes the problem. So it seems there is something off with the way orthofinder looks for its config file...

Cheers
Thomas

**Comment by davidemms** [comment]
Hi Thomas

This appears to affect the binary version but not the python source code version. I'll look into it.

Thanks
David

**Comment by thackl** [comment]
Great, thanks for the quick fix!

**Comment by davidemms** [comment]
This has now been fixed in the binary package in version v1.1.8.

**Comment by twohrdrive** [comment]
Hi All,

I have the latest diamond (0.9.24) and orthofinder (2.3.3) versions.  I can run orthofinder with the -h option so it seems to work. DIAMOND is also in my path because I can type "diamond --version" in any directory and get the version.  I also added orthofinder to PATH.  both diamond and orthofinder binaries are in ~/bin.  

But I am still getting this same error code when trying to run orthofinder on the example files using:

$orthofinder -f ExampleData/ -S diamond

and receiving the error:

Invalid argument for option -S: diamond
Valid options are: {blast}

Any advice? Many thanks in advance!

**Comment by davidemms** [comment]
Hi

You need to have the "config.json" file in the same directory as orthofinder, it contains information for orthofinder on how to call diamond.

All the best
David

**Comment by twohrdrive** [comment]
Dear David,

That seemed to work. Thank you so much!!! And thank you for the amazing package:)

-A
